services:
  pg_db_test:
    image: postgres
    container_name: pg_db_test
    restart: always
    ports:
      - 4215:5432
    env_file:
      - .env.test

  node_app_test:
    container_name: node_app_test
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env.test
    depends_on:
      - pg_db_test